import { DeviceBreakdown, PeakHourPoint, Restaurant, ScanTrendPoint } from "./restaurant";


export const MOCK_RESTAURANTS: Restaurant[] = [
  {
    id: "sakura-ramen-house",
    name: "Sakura Ramen House",
    location: "Downtown District",
    scans: 4820,
    menuViews: 6210,
    weeklyTrendPct: 12.4,
    status: "active",
    onboardedLabel: "Jan 2025",
    color: "#6C4DF4",
    menuUrl: "https://menuscan.app/m/sakura-ramen",
  },
  {
    id: "bella-vista-trattoria",
    name: "Bella Vista Trattoria",
    location: "Riverside Ave",
    scans: 3990,
    menuViews: 5100,
    weeklyTrendPct: 8.1,
    status: "active",
    onboardedLabel: "Mar 2025",
    color: "#00BFA6",
    menuUrl: "https://menuscan.app/m/bella-vista-trattoria",
  },
  {
    id: "el-toro-steakhouse",
    name: "El Toro Steakhouse",
    location: "Grand Plaza",
    scans: 3510,
    menuViews: 4460,
    weeklyTrendPct: -3.2,
    status: "active",
    onboardedLabel: "Feb 2025",
    color: "#FF6B6B",
    menuUrl: "https://menuscan.app/m/el-toro-steakhouse",
  },
  {
    id: "blue-lotus-cafe",
    name: "Blue Lotus Café",
    location: "Harbor Walk",
    scans: 2870,
    menuViews: 3690,
    weeklyTrendPct: 5.6,
    status: "paused",
    onboardedLabel: "Nov 2024",
    color: "#3D8BFF",
    menuUrl: "https://menuscan.app/m/blue-lotus-cafe",
  },
  {
    id: "the-grain-bowl",
    name: "The Grain Bowl",
    location: "Market Street",
    scans: 2340,
    menuViews: 3010,
    weeklyTrendPct: 15.9,
    status: "active",
    onboardedLabel: "May 2025",
    color: "#FFA63D",
    menuUrl: "https://menuscan.app/m/the-grain-bowl",
  },
  {
    id: "nonnas-kitchen",
    name: "Nonna's Kitchen",
    location: "Old Town",
    scans: 1980,
    menuViews: 2540,
    weeklyTrendPct: 2.3,
    status: "active",
    onboardedLabel: "Apr 2025",
    color: "#F651A8",
    menuUrl: "https://menuscan.app/m/nonnas-kitchen",
  },
];

export const MOCK_SCAN_TREND: ScanTrendPoint[] = [
  { label: "D1", scans: 210, ordersStarted: 80 },
  { label: "D2", scans: 240, ordersStarted: 95 },
  { label: "D3", scans: 265, ordersStarted: 100 },
  { label: "D4", scans: 230, ordersStarted: 90 },
  { label: "D5", scans: 300, ordersStarted: 120 },
  { label: "D6", scans: 340, ordersStarted: 140 },
  { label: "D7", scans: 320, ordersStarted: 130 },
  { label: "D8", scans: 360, ordersStarted: 150 },
  { label: "D9", scans: 410, ordersStarted: 170 },
  { label: "D10", scans: 390, ordersStarted: 160 },
  { label: "D11", scans: 430, ordersStarted: 175 },
  { label: "D12", scans: 470, ordersStarted: 195 },
  { label: "D13", scans: 455, ordersStarted: 188 },
  { label: "D14", scans: 510, ordersStarted: 210 },
];

export const MOCK_DEVICE_BREAKDOWN: DeviceBreakdown = {
  mobilePct: 78,
  tabletPct: 15,
  desktopPct: 7,
};

export const MOCK_PEAK_HOURS: PeakHourPoint[] = [
  { hourLabel: "8a", scans: 8 },
  { hourLabel: "10a", scans: 20 },
  { hourLabel: "12p", scans: 65 },
  { hourLabel: "2p", scans: 40 },
  { hourLabel: "4p", scans: 25 },
  { hourLabel: "6p", scans: 55 },
  { hourLabel: "8p", scans: 90 },
  { hourLabel: "10p", scans: 42 },
];